### ISSUE TITLE
接口评审

### ISSUE THREAD

**Issue by cleverpp** [kayuanweb/rap2-dolores#17]
评审通过后，再次编辑接口属性，例如添加一个请求参数，或添加一个相应参数，无法再次发起评审。

常见的场景是：接口相关描述变化比较少，而接口的请求参数、响应参数 的增、删 比较多。
建议控制到请求参数、响应参数的 增删 这个级别。

请求参数、响应参数的 取值更新 不需要考虑， 但是 name 更新也需要考虑。

**Comment by cleverpp** [comment]
涉及以下修改，需要更新评审状态：
接口： 修改 name，url，method
属性： 新增属性、删除属性，修改name

**Comment by tuntun5011** [comment]
已修改，提交pull request
