### ISSUE TITLE
添加了新的团队和仓库，但是地图中并未更新显示新增团队的内容

### ISSUE THREAD

**Issue by cleverpp** [kayuanweb/rap2-dolores#47]
问题如题。

初步分析，因为你的地图使用的是单独的缓存MAP，你的缓存更新应该存在问题。

**Comment by QTFYING** [comment]
是的，我直接把数据读取后直接就缓存了，在团队，仓库，模块，接口进行增删改的时候应该把map接口的redis缓存给清空一下
